;;
;; Oblivion theme ported from Gedit
;;
(set-background-color "#2e3436")
(set-foreground-color "#d3d7cf")
(set-face-background 'default "#2e3436")
(set-face-foreground 'default "#d3d7cf")
(set-cursor-color "#d3d7cf")
(set-face-background 'highlight "#555753")
;(set-face-foreground 'linum "#555753")
;(set-face-background 'linum "#000000")
(set-face-foreground 'font-lock-comment-face "#888a85")
(set-face-italic-p 'font-lock-comment-face t)
(set-face-foreground 'font-lock-doc-face "#888a85")
(set-face-italic-p 'font-lock-doc-face t)
(set-face-foreground 'font-lock-constant-face "#e5786d")
(set-face-foreground 'font-lock-string-face "#edd400")
;; (set-face-foreground 'font-lock-variable-name-face "#8ae234")
(set-face-foreground 'font-lock-variable-name-face "#d3d7cf")
(set-face-bold-p 'font-lock-variable-name-face t)
(set-face-foreground 'font-lock-function-name-face "#729fcf")
(set-face-foreground 'font-lock-type-face "#8ae234")
(set-face-foreground 'font-lock-builtin-face "#8ac6f2")
(set-face-foreground 'font-lock-keyword-face "#ad7fa8")
;; (set-face-foreground 'font-lock-keyword-face "#FFFFFF")
;; (set-face-bold-p 'font-lock-keyword-face t)
;; (set-face-foreground 'font-lock-preprocessor-face "#e5786d")
(set-face-foreground 'font-lock-negation-char-face "#e7f6da")
(set-face-foreground 'link "#8ac6f2")
 (set-face-bold-p 'link t)
(set-face-underline-p 'link t)
;;(show-paren-mode 1)
(set-face-foreground 'show-paren-match "#eeeeec")
;; (set-face-foreground 'show-paren-match "#E48A17")
(set-face-background 'show-paren-match "#BEBEBE")
;; (set-face-background 'show-paren-match "#8a8a8a")
(set-face-bold-p 'show-paren-match t)
(set-face-foreground 'show-paren-mismatch "#eeeeec")
(set-face-background 'show-paren-mismatch "#babdb6")
(set-face-foreground 'region "#eeeeec")
(set-face-background 'region "#888a85")
(set-face-foreground 'lazy-highlight "black")
(set-face-background 'lazy-highlight "yellow")
(set-face-foreground 'fringe "#d3d7cf")
(set-face-background 'fringe "#2e3436")
